atlassian/jira-actions

- .travis.yml
- CHANGELOG.md
- build.gradle.kts
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/page/CommentForm.kt
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/page/EditIssuePage.kt
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/page/RichTextEditorTextArea.kt
- src/test/kotlin/com/atlassian/performance/tools/jiraactions/api/scenario/JiraCoreScenarioIT.kt
- src/test/kotlin/com/atlassian/performance/tools/jiraactions/api/scenario/RichTextEditorIT.kt
- src/test/resources/log4j2.xml
Source: https://github.com/atlassian/jira-actions/pull/3
> JPERF-184 Add support for Rich Text Editor

- CHANGELOG.md
https://travis-ci.com/atlassian/jira-actions/builds/109737834
> Mark release 3.5.0

- CHANGELOG.md
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/action/ViewIssueAction.kt
- src/test/kotlin/com/atlassian/performance/tools/jiraactions/api/scenario/JiraCoreScenarioIT.kt
Included observations enable us to match performance results and underlying data.
> Observations added to View Issue action.

- .editorconfig
- .travis.yml
- CHANGELOG.md
https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/jira-actions/3.5.1/
> Mark 3.5.1

- CHANGELOG.md
https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/jira-actions/3.7.0/
> Mark 3.7.0 release

- CHANGELOG.md
- README.md
https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/jira-actions/3.8.0/
> Mark 3.8.0

- CHANGELOG.md
https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/jira-actions/3.9.0/
> Mark 3.9.0 release

- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/page/AdminAccess.kt
this shortents the dev loop on jira-actions by one minute per single test using AdminAccess
> take shortcuts in AdminAccess

- CHANGELOG.md
Artifacts: https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/jira-actions/3.10.3/
> Mark 3.10.3 release

- CHANGELOG.md
https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/jira-actions/3.11.0/
> Mark 3.11.0 release

- CHANGELOG.md
https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/jira-actions/3.12.0/
> Mark 3.12.0 release

- CHANGELOG.md
Artifacts: https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/jira-actions/3.13.0/
> Mark 3.13.0 release

- CHANGELOG.md
Artifacts: https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/jira-actions/3.13.1/
> Mark 3.13.1 release

- CHANGELOG.md
Artifacts: https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/jira-actions/3.13.2/
> Mark 3.13.2 release

- CHANGELOG.md
Artifacts: https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/jira-actions/3.13.3/
> Mark 3.13.3 release

- CHANGELOG.md
Artifacts: https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/jira-actions/3.13.4/
> Mark 3.13.4 release

- .github/workflows/ci.yml
GHA CI will be initially red as we need to bump testcontainers library in order for the tests to be green. I'll do it in a separate PR, so that we can see the actual results on GHA.
> Introduce GitHub Actions configuration

- CHANGELOG.md
Artifacts: https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/jira-actions/3.15.1/
> Mark 3.15.1 release

- CHANGELOG.md
https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/jira-actions/3.18.1/
> Mark 3.18.1 release

- CHANGELOG.md
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/action/SearchIssues.kt
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/action/SearchJqlAction.kt
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/action/SearchJqlChangelogAction.kt
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/action/SearchJqlSimpleAction.kt
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/action/SearchJqlWildcardAction.kt
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/page/IssueNavigatorPage.kt
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/page/issuenav/DetailView.kt
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/page/issuenav/IssueNavResultsView.kt
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/page/issuenav/ListView.kt
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/scenario/JiraCoreScenario.kt
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/memories/jql/TagSelectiveJqlMemory.kt
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/page/issuenav/UnknownView.kt
> JPERF-1043: list view support - addressing code review

- CHANGELOG.md
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/action/ActionSequence.kt
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/action/DismissCommentPinDiscovery.kt
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/scenario/JiraCoreScenario.kt
Dissmiss pin comment discovery dialog when visiting issue.
> JPERF-1102 Add DismissCommentPinDiscovery action.

- CHANGELOG.md
https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/jira-actions/3.21.0/
> Mark 3.21.0 release

- CHANGELOG.md
https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/jira-actions/3.21.1/
> Mark 3.21.1 release

- CHANGELOG.md
https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/jira-actions/3.21.2/
> Mark 3.21.2

- CHANGELOG.md
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/w3c/PerformanceResourceTiming.kt
- src/main/kotlin/com/atlassian/performance/tools/jiraactions/api/w3c/PerformanceServerTiming.kt
https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/jira-actions/3.24.0/
> Mark 3.24.0

- CHANGELOG.md
https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/jira-actions/3.28.1/
> Mark 3.28.1
